### ISSUE TITLE
Official Name?

### ISSUE THREAD

**Issue by kbruegge** [open-gamma-ray-astro/gamma-astro-data-formats#134]
The docs and the readme use 
> Data formats for gamma-ray astronomy

which is more of a general description than a name. Does introducing a name make sense to you? Maybe something more catchy like 'open gamma-ray data description (OGDD)' or something.

**Comment by cdeil** [comment]
It's true we don't have a "name" for this project, and I also think having one is nice because it lets you talk about it more easily and lets people remember and find (and Google) it.

But for this project, nothing good comes to mind, and making something arbitrary up that's non-descriptive doesn't seem useful.

If we just use abbreviations, I would suggest to use the ones we kind of already have:
- GADF = Gamma Astro Data Formats
- OGRA = Open Gamma Ray Astro

Mentioning those abbreviations in the README and docs would be good IMO.

@mackaiver - Thoughts?

**Comment by micheledoro** [comment]
OGRAD = Open Gamma Ray Open Architectures and Data

**Comment by TarekHC** [comment]
This is fun!

Maybe this feels a bit more natural?
OGRAP = Open Gamma Ray Analysis Products
FOGRAP = Format for Open Gamma Ray Analysis Products

**Comment by cboisson** [comment]
But Architecture as proposed by Michele  is important too.

That being said, in my opinion having too precise name and too many projects with only one aim (publihing data in an open faitr way) may be confusing. So I would keep just "Data formats for gamma-ray astronomy".

The addition of ASTRO to gamma data was already odd.

**Comment by cdeil** [comment]
> The addition of ASTRO to gamma data was already odd.

We added "astro" because there's a lot of gamma-rays and gamma-ray data that's not from astronomy. See https://en.wikipedia.org/wiki/Gamma_ray
E.g. you can find open data concerning gamma-rays from nuclear physics or radiation levels or ...

So I would keep the "astro" in the name.

---

To be honest, none of the new proposals here seem better to me than what we chose a few years ago and have now.

Changing the names and https://github.com/open-gamma-ray-astro/gamma-astro-data-formats or https://lists.nasa.gov/mailman/listinfo/open-gamma-ray-astro IMO would need a clearly better name, and someone that plans to actively work on this project. While these names haven't been used widely, they have been used a bit, e.g. in https://arxiv.org/pdf/1610.01884.pdf .

**Comment by cboisson** [comment]
Sure  that gamma-ray can be a lot of things, but "astro" gamma too. Not only GeV-TeV . 
I was not asking to change anything that is already there, just to not add unnecessary acronyms.
A description, so clear set f words, is always best unless you create that with others that are ready to endorse it like FITS.

But I will not complain with any acronym, just go on.

**Comment by kosack** [comment]
I like "*Data Models For Open Gamma-ray Astronomy*" or "*Data Formats for Gamma-ray Astronomy*" as the title, and something shorter but memorable like "gammaray-formats"  or "gammaray-data" as the repo name.

**Comment by maxnoe** [comment]
I think this ship has sailed long-ago and we are now simply known as GADF everywhere...

Also with the imminent  handover to VODF, I am closing this issue.
