### ISSUE TITLE
Effective area in estimated energy: How?

### ISSUE THREAD

**Issue by MaxNoe** [open-gamma-ray-astro/gamma-astro-data-formats#137]
The website states: 

> In the case of using the effective area as a function of reconstructed energy, results may be less precise, but require less MC statistics and allows to perform faster likelihood fits by science tools.

How can you express effective area in estimated energy when effective area is the ratio of selected events of all simulated events and there is no estimated energy for the events that did not trigger / were not selected by a pre-selection / did not survive image cleaning?

**Comment by lmohrmann** [comment]
That is a valid concern I think, yes. We know the number of simulated events only as a function of true energy, so we need to divide by that. This means that in principle one should of course divide the number of selected events vs true energy by the number of simulated events vs true energy, and then use an energy dispersion matrix in the analysis.

I guess the idea behind the statement on the website is: if we assume that reco energy=true energy, we might as well divide the number of selected events vs reco energy by the number of simulated events vs true energy, _thus signaling that the energy dispersion matrix is considered diagonal and need not be included in the analysis_. Whether it's a good idea to make this assumption or not is another question of course...

Do you feel we should provide a better explanation of this? If so, can you propose one?

**Comment by MaxNoe** [comment]
Yes, I can come up with one early next year. I think we should give a proper definition of effective area (only vs. simulated energy) and note that for certain cases it might be ok to assume E_true ≈ E_est

**Comment by relleums** [comment]
Thank you Max for asking how the effective area can be in reconstructed energy. I just read [ ```v0.2```](https://gamma-astro-data-formats.readthedocs.io/en/v0.2/irfs/irf_components/index.html) on ```readthedocs``` and got exactly this question, too.

Since [ ```v0.2```](https://gamma-astro-data-formats.readthedocs.io/en/v0.2/irfs/irf_components/index.html) mentions the possibility of having either true or 'estimated' energy I wonder if there should be a flag/indication in the ```HDU```'s header whether the energy is true energy or estimated energy.

Is the energy now implicitly the true energy? So no flag is needed?

I also think the IRF's effective area for gamma-rays should always be in true energy.

I think I see where this estimated energy thing comes from. In some estimates of differential sensitivity there is an area used for gamma-rays which is NOT the effective area, but some convoluted area, e.g. convoluted with the energy-dispersion. I think CTA's estimate is done this way. And this is also fine. It has a valid astronomical use. It means that you will accept gamma-rays with true energies outside of your energy-bin to be a part of your signal. This would be misleading when your source emits only in a narrow band, but makes somewhat sense when the emission of the source is broad and you care more about the detection itself rather than the correct energies.
But one must not confuse this 'convoluted area' with the effective area estimated in simulations.
