### ISSUE TITLE
Format of TSTART and TSTOP in obs-index table not defined consistently

### ISSUE THREAD

**Issue by lmohrmann** [open-gamma-ray-astro/gamma-astro-data-formats#95]
The format of the fields TSTART and TSTOP is not defined consistently. On [this page](http://gamma-astro-data-formats.readthedocs.io/en/latest/general/time.html), it says the values are stored in MJD, whereas [this page](http://gamma-astro-data-formats.readthedocs.io/en/latest/data_storage/obs_index/index.html#obs-index) says they are stored in MET. Which one do we want?

Note that TSTART and TSTOP are also keywords of the EVENTS extension, where they are stored in MET.

**Comment by cdeil** [comment]
@lmohrmann - Thanks for filing the issue!

I think we struggled with adopting the FITS time standard with the reference time header keywords as used in EVENTS for OBSINDEX because we said it should be more like a "runlist" that is human-readable and that can be stored in CSV files that don't support a header and that time format.

But looking back, I think that was a mistake, because it causes a lot of complexity with time-related information, and we should just require the same time format that we already use for EVENTS.

My understanding is that backward compatibility isn't a bit concern yet.
The first observation index for CTA was made recently, and uses the FITS way to define times already (I hope):
https://github.com/gammasky/cta-dc/blob/e6cdb0567340d23fa14fe9ae400d3bcdb7899281/data/cta_1dc_make_data_index_files.py#L215
MAGIC is just starting to use this, and the main use comes from HESS and Gammapy, and we should really aim to clean this up before the first HESS data release, to avoid having a mess for the coming years.

@lmohrmann - Can you make a pull request to improve this aspect (or even anything else that you notice) concerning the obs index table?
